version: '3.7'

services:
    mongodb:
        image: mongo:latest
        container_name: wfd-mongo
        environment:
            MONGO_INITDB_DATABASE: wfd
            MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER}
            MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PW}
        ports:
            - 27017:27017
        volumes:
            - ./init-local-mongo.js:/docker-entrypoint-initdb.d/init-local-mongo.js